"""A realistic lecture, jotted the way a student actually types.

Half of it has no markup at all; some lines are fragments, some are
run-ons, some are LaTeX. Used by tests/test_lecture.py (assertions) and
tools/lecture.py (eyeballing). Each entry is one thing the student typed
and let go of.
"""

# (text, typed_with) -- "commit" is a finished thought filed on its own,
# "compose" goes through the composer keystroke by keystroke so the
# sentence detector has to earn it.
STREAM = [
    ("# Thermo 3 - entropy", "commit"),
    ("prof started 5 min late again", "commit"),
    ("## The second law", "commit"),
    ("entropy always increases in an isolated system. ", "compose"),
    ("entropy :: a measure of how many microstates match one macrostate", "commit"),
    ("$$S = k_B \\ln \\Omega$$", "commit"),
    ("$k_B$ is Boltzmann's constant, about $1.38 \\times 10^{-23}$ J/K", "commit"),
    ("so more ways to arrange the same energy means more entropy. ", "compose"),
    ("- reversible: $\\Delta S = 0$", "commit"),
    ("- irreversible: $\\Delta S > 0$", "commit"),
    ("  - all real processes are irreversible", "commit"),
    ("- the universe as a whole: $\\Delta S \\geq 0$ always", "commit"),
    ("wait is entropy extensive or intensive?", "commit"),
    ("extensive, it scales with the amount of stuff", "commit"),
    ("TODO check the microstate counting example in ch 4", "commit"),
    ("---", "commit"),
    ("## Clausius and heat flow", "commit"),
    ("for a reversible path the entropy change is an integral of dQ over T. ", "compose"),
    ("$$\\Delta S = \\int_{T_1}^{T_2} \\frac{C_p}{T} dT$$", "commit"),
    ("careful: only along a reversible path", "commit"),
    ("!this is on the midterm", "commit"),
    ("heat always flows hot to cold because the total $\\Delta S$ has to be positive. ",
     "compose"),
    ("worked example: 1 kg of ice at 0 C melting in a warm room. ", "compose"),
    ("ice gains $\\frac{Q}{273}$, room loses $\\frac{Q}{298}$, net positive", "commit"),
    ("- $Q = mL = 334$ kJ", "commit"),
    ("- $\\Delta S_{ice} = 1223$ J/K", "commit"),
    ("- $\\Delta S_{room} = -1121$ J/K", "commit"),
    ("- net: $+102$ J/K", "commit"),
    ("## Heat engines", "commit"),
    ("efficiency: $\\eta = 1 - T_c/T_h$", "commit"),
    ("no engine beats Carnot, that is the whole point of the second law. ", "compose"),
    ("engine | T_h (K) | T_c (K) | efficiency", "commit"),
    ("carnot ideal | 800 | 300 | 0.63", "commit"),
    ("steam plant | 810 | 300 | 0.42", "commit"),
    ("car petrol | 2000 | 600 | 0.25", "commit"),
    ("real ones lose to friction and non-equilibrium heat transfer", "commit"),
    ("Ideal || Real", "commit"),
    ("no molecular volume || molecules take up space", "commit"),
    ("no attractions || van der Waals forces matter", "commit"),
    ("$$PV = nRT$$ || $$(P + \\frac{an^2}{V^2})(V - nb) = nRT$$", "commit"),
    ("T-S diagrams:", "commit"),
    ("she drew the T-S diagram twice, the second one is the right one", "commit"),
    ("area under the curve on a T-S diagram is heat", "commit"),
    ("TODO redraw the T-S diagram from the slides", "commit"),
    ("## Statistical view", "commit"),
    ("$$\\Omega = \\frac{N!}{n_1! n_2!}$$", "commit"),
    ("for large N use Stirling: $\\ln N! \\approx N \\ln N - N$", "commit"),
    ("this is where the $k_B \\ln \\Omega$ form comes from. ", "compose"),
    ("- macrostate: what you can measure", "commit"),
    ("- microstate: one specific arrangement", "commit"),
    ("  - there are absurdly many of them", "commise"),
    ("free energy :: the part of the energy that can still do work", "commit"),
    ("$$G = H - TS$$", "commit"),
    ("a reaction goes forward when $\\Delta G < 0$", "commit"),
    ("so entropy can drive a reaction even when it costs energy. ", "compose"),
    ("exam is the 14th, two of the five questions are entropy", "commit"),
    ("she said the problem set is due friday not thursday", "commit"),
    ("TODO email her about the extension", "commit"),
]
